emindprinterbackend  usr/lib/emindprinter/emindprinterbackend
#usr/lib/emindprinter/emindprintermerger
emindprinter usr/lib/cups/backend/emindprinter
#usr/lib/cups/filter/emindprinter_pstopdf
#usr/share/applications/emindprinter.desktop
#usr/share/emindprinter/translations/emindprinterer_*.qm
org.emindprinterer.service usr/share/dbus-1/services/org.emindprinterer.service
#usr/share/icons/hicolor/128x128/apps/emindprinter.png
#usr/share/icons/hicolor/16x16/apps/emindprinter.png
#usr/share/icons/hicolor/32x32/apps/emindprinter.png
#usr/share/icons/hicolor/64x64/apps/emindprinter.png
#usr/share/man/man1/emindprinter.1.gz
#usr/share/mime/packages/emindprinter.xml
emindprinter.ppd usr/share/ppd/emindprinter/emindprinter.ppd
